image:
  repository: tanishaart/complete-devops-project
  tag: 93b06d1
  pullPolicy: IfNotPresent
service: 
  type: clusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false