image:
  repository: tanishaart/complete-devops-project
  tag: 7d023b4
  pullPolicy: IfNotPresent
service: 
  type: clusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
httpRoute:
  enabled: true